#
# Run repoman via travis
# See https://github.com/mrueg/repoman-travis
#
language: python
python:
    - pypy
env:
    - PORTAGE_VER="2.3.66"
before_install:
    - sudo apt-get -qq update
    - pip install lxml pyyaml
    - sudo apt install shellcheck
before_script:
    - sudo mkdir -p /var/db/repos/gentoo /var/cache/distfiles
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /usr /usr/local /var/db/repos/gentoo /var/cache/distfiles
    - mkdir -p travis-overlay /etc/portage
    - mv !(travis-overlay) travis-overlay/
    - mv .git travis-overlay/
    #- wget "https://raw.githubusercontent.com/mrueg/repoman-travis/master/.travis.yml" -O .travis.yml.upstream
    - wget "https://raw.githubusercontent.com/mrueg/repoman-travis/master/spinner.sh"
    - wget -qO - "https://github.com/gentoo/portage/archive/portage-${PORTAGE_VER}.tar.gz" | tar xz
    - wget -qO - "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" | tar xz -C /var/db/repos/gentoo --strip-components=1
    - chmod a+rwx spinner.sh
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
    - mkdir -p /etc/portage/repos.conf
    - ln -s $TRAVIS_BUILD_DIR/portage-portage-${PORTAGE_VER}/cnf/repos.conf /etc/portage/repos.conf/gentoo.conf
    - ln -s $TRAVIS_BUILD_DIR/travis-overlay/testconfig/mv.conf /etc/portage/repos.conf/mv.conf
    - ln -s /usr/portage/profiles/default/linux/amd64/17.1 /etc/portage/make.profile
    - cd /usr/local
    - git clone --depth 1 https://github.com/vaeth/mv-overlay mv
    - sudo chmod a+rwX mv
    - cd $TRAVIS_BUILD_DIR
    #- SIZE=$(stat -c %s .travis.yml.upstream)
    #- if ! cmp -n $SIZE -s .travis.yml .travis.yml.upstream; then echo -e "\e[31m !!! .travis.yml outdated! Update available https://github.com/mrueg/repoman-travis \e[0m" > /tmp/update ; fi
    - cd travis-overlay
script:
    - ./../spinner.sh "shellcheck app-portage/lto-rebuild/files/lto-rebuild" #Tests to ensure lto-rebuild plays nice with shells other than Bash
    - ./../spinner.sh "python ../portage-portage-${PORTAGE_VER}/repoman/bin/repoman full -dx"
# You can append own scripts after this line
